### ISSUE TITLE
whois on valid .ie domain results in 10006 error

### ISSUE THREAD

**Issue by senf666** [ip2whois/ip2whois-python#2]
Hi,
I'm using the api as follows

```
import ip2whois

ip2whois_init = ip2whois.Api('xxxxxxxxxx')
result = ip2whois_init.lookup('daft.ie')

print(result)
```

The above code results in the following response:

`{'error': {'error_code': 10006, 'error_message': 'No data found.'}`

This is incorrect. The domain daft.ie is valid. A valid whois output can be viewed [here](https://www.weare.ie/whois-result/?whois=daft.ie).

the [website](https://www.ip2whois.com) whois lookup also fails

<img width="387" alt="image" src="https://user-images.githubusercontent.com/3512672/211684024-ace9eaeb-a135-4002-9ee3-bda13421d3ce.png">

I hope you can fix this as I'm looking forward to using your api. 
thanks.

**Comment by ip2whois** [comment]
Hi,

We have fixed the issue. Kindly try it again.

**Comment by senf666** [comment]
working, super speedy resolution, thanks.
